// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Neron":return img`
........................
........................
........................
........................
........................
........................
........................
........................
........ff..............
.....ffff2ff............
...ffeeeef2ff...........
..ffeeeeef22ff..........
..feeeeffeeeef..........
..fffffee2222ef.........
.fffe222ffffe2f.........
.ffffffffeeefff.........
.fefe44ebf44eef.........
..fee4d4bfddef..........
...feee4dddee.c.........
....f2222eeddeccccccc...
....f444e44ddecddddd....
....fffffeeee.ccccc22...
...ffffffff...c.........
...fff..ff..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
